#ifndef ENUMS_H
#define ENUMS_H

enum TOOL {PENCIL, ERASER, CIRCLE, TRIANGLE, RECTANGLE, POLYGON, SELECT, NOTOOL};

enum COLOR {RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET};

enum ACTION {NONE, CLEAR, UNDO, PLUS, MINUS, FRONT, BACK, CCHANGE};

#endif